#### 异常

##### `try` 语句

当 `try` 语句启动时， `Python` 会标识当前的程序上下文，这样一来，如果之后有异常发生时，才能返回这里。 `try` 首行下的语句会率先执行，若 `try` 中引发了异常，则执行后续的异常捕捉语句 `except` 。若 `try` 代码块内发生了异常，且在 `except` 中没有找到相应的匹配，则异常会向上传递到程序之前最近一次进入的能够匹配的 `try` 中，如果依然不能找到，则继续向上，直到打印一条默认错误信息。若在 `try` 代码块中没有发生异常，则执行 `else` 代码块中的语句（如果有的话），之后控制权会从整个 `try` 语句的后面继续。

示例：

语法：

```python
try:
    statements 
except name1: #捕捉指定的异常
    statements
except (name2, name3): #捕捉列出的异常
    statements
except name4 as value: #捕捉指定的异常，并将异常实例赋值给名称 value
    statements
except (name2, name3) as value: #捕捉列出的异常，并将异常实例元组赋值给名称 value
except: #捕捉所有的异常
    statements
else: #没有引发异常时执行，else是可选的，但else时，必须至少有一个except
    statements
finally: #总是在退出 try 语句时运行
    statement
```

`Python` 会从上到下的执行异常捕捉语句，并执行第一个匹配的异常捕捉语句。

`except Exception:` 与 `except:` 都是是捕获所有异常，但 `except:` 可系统退出调用的异常也捕获到（系统退出调用是通过触发异常来实现的），但`except Exception:` 不会捕获与系统退出有关的异常。

##### 捕获内置异常

一般情况下当程序出错时，会默认终止程序，若想要程序不终止运行，可以捕获异常，然后进行异常处理，这样可以保证程序不终止运行。

##### `raise` 传递异常

`raise` 可以重新引发当前异常，一般如果需要捕获和处理一个异常，有不希望异常在程序代码中死掉，就会使用 `raise` 重新引发异常，例如，将异常抛给上个 `try` 块。

```python
try:
    try:
        raise IndexError("spam") #抛出一个异常
    except IndexError: #捕获异常
        print("error-one")
        raise #再次引发异常，传递给外层的 try
except IndexError: #捕获内层传递过来的异常
    print("error-two")
    raise #再次引发异常，此时异常传递给了系统默认的异常处理
#输出：
error-one
error-two
IndexError
```

##### 异常的使用

1. 跳出多重嵌套循环

   ```python
   #使用break跳出多层循环
   while True:
       while True:
           for i in range(10):
               print("one", i)
               if i > 3: 
                   break #跳出for循环
           print("two")
           break #跳出while循环
           print("thr")
       break #跳出while循环
   print("aioverg")
   
   #使用异常跳出多层循环
   try:
       while True:
           while True:
               for i in range(10):
                   if i > 3: raise IndexError("catch")
                   print("one", i)
               print("two")
           print("thr")
   except IndexError:
       print("aioverg")
   #输出：
   one 0
   one 1
   one 2
   one 3
   aioverg
   ```

   Python 中的 `break` 只能跳出最近的一个循环，而利用异常则可以跳出更多层的循环。

2. 略